apiVersion: research.dynatrace.com/v1alpha1
kind: DeceptionPolicy
metadata:
  name: deceptionpolicy-authtoken-passwords
spec:
  strictValidation: true
  mutateExisting: true

  traps:
    - filesystemHoneytoken:
        filePath: /tmp/auth_token.json
        fileContent: >
          {"token": "someverysecrettoken"}
        readOnly: true

      match:
        any:
          - resources:
              containerSelector: "*"
              selector:
                matchLabels:
                  demo.koney/honeytoken: "true"

      decoyDeployment:
        strategy: containerExec
      captorDeployment:
        strategy: tetragon

    - filesystemHoneytoken:
        filePath: /tmp/passwords.txt
        fileContent: >
          admin:password
        readOnly: true

      match:
        any:
          - resources:
              containerSelector: "*"
              selector:
                matchLabels:
                  demo.koney/honeytoken: "true"

      decoyDeployment:
        strategy: containerExec
      captorDeployment:
        strategy: tetragon
